update

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -49,22 +49,10 @@ jobs:
             -p 5007:5007 \
             ${{ vars.RASA_IMAGE }} \
             run actions \
-            --port 5007 \
+            --port 5007
             #--cors "*"
 
       - name: Run inspect
-        run: |
-          sudo docker run --restart unless-stopped -d -v ${GITHUB_WORKSPACE}:/app \
-            -e RASA_PRO_LICENSE=${{ secrets.RASA_PRO_LICENSE }} \
-            -u $(id -u) \
-            --name github_runner_dgcas2024_rasa_inspect \
-            -p 5006:5006 \
-            ${{ vars.RASA_IMAGE }} \
-            inspect --model /app/models --endpoints /app/endpoints.yml \
-            --port 5006 \
-            #--cors "*"
-
-      - name: Run model
         run: |
           sudo docker run --restart unless-stopped -d -v ${GITHUB_WORKSPACE}:/app \
             -e RASA_PRO_LICENSE=${{ secrets.RASA_PRO_LICENSE }} \
@@ -72,16 +60,35 @@ jobs:
             -e FACEBOOK_SECRET=${FACEBOOK_SECRET} \
             -e FACEBOOK_PAGE_ACCESS_TOKEN=${FACEBOOK_PAGE_ACCESS_TOKEN} \
             -u $(id -u) \
-            --name github_runner_dgcas2024_rasa \
-            -p 5005:5005 \
+            --name github_runner_dgcas2024_rasa_inspect \
+            -p 5006:5006 \
             ${{ vars.RASA_IMAGE }} \
-            run --model /app/models --endpoints /app/endpoints.yml --credentials /app/credentials.yml --enable-api \
-            --port 5005 \
+            inspect --model /app/models --endpoints /app/endpoints.yml \
+            --port 5006
             #--cors "*"
         env:
           FACEBOOK_VERIFY: ${{ secrets.FACEBOOK_VERIFY }}
           FACEBOOK_SECRET: ${{ secrets.FACEBOOK_SECRET }}
           FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
+
+      #- name: Run model
+      #  run: |
+      #    sudo docker run --restart unless-stopped -d -v ${GITHUB_WORKSPACE}:/app \
+      #      -e RASA_PRO_LICENSE=${{ secrets.RASA_PRO_LICENSE }} \
+      #      -e FACEBOOK_VERIFY=${FACEBOOK_VERIFY} \
+      #      -e FACEBOOK_SECRET=${FACEBOOK_SECRET} \
+      #      -e FACEBOOK_PAGE_ACCESS_TOKEN=${FACEBOOK_PAGE_ACCESS_TOKEN} \
+      #      -u $(id -u) \
+      #      --name github_runner_dgcas2024_rasa \
+      #      -p 5005:5005 \
+      #      ${{ vars.RASA_IMAGE }} \
+      #      run --model /app/models --endpoints /app/endpoints.yml --credentials /app/credentials.yml --enable-api \
+      #      --port 5005
+      #      #--cors "*"
+      #  env:
+      #    FACEBOOK_VERIFY: ${{ secrets.FACEBOOK_VERIFY }}
+      #    FACEBOOK_SECRET: ${{ secrets.FACEBOOK_SECRET }}
+      #    FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
 
       - name: Validate URL
         run: |
@@ -100,7 +107,7 @@ jobs:
 
           echo "Waiting for inspect to be ready..."
           timeout=300
-          while ! curl --output /dev/null --silent --fail http://127.0.0.1:5006; do
+          while ! curl --output /dev/null --silent --fail http://127.0.0.1:5006/status; do
             echo "Waiting for inspect to be ready...$timeout"
             sleep 1
             timeout=$((timeout-1))
@@ -111,15 +118,15 @@ jobs:
           done
           echo "Inspect is ready."
 
-          echo "Waiting for server to be ready..."
-          timeout=300
-          while ! curl --output /dev/null --silent --fail http://127.0.0.1:5005/status; do
-            echo "Waiting for server to be ready...$timeout"
-            sleep 1
-            timeout=$((timeout-1))
-            if [ "$timeout" -le 0 ]; then
-              echo "Timeout when start server."
-              exit 1
-            fi
-          done
-          echo "Server is ready."
+          #echo "Waiting for server to be ready..."
+          #timeout=300
+          #while ! curl --output /dev/null --silent --fail http://127.0.0.1:5005/status; do
+          #  echo "Waiting for server to be ready...$timeout"
+          #  sleep 1
+          #  timeout=$((timeout-1))
+          #  if [ "$timeout" -le 0 ]; then
+          #    echo "Timeout when start server."
+          #    exit 1
+          #  fi
+          #done
+          #echo "Server is ready."
